# readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/requirements.yaml

python:
  install:
    - method: pip
      path: .

jobs:
  post_build:
    - python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir .
    - python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html || true