name: ggmolvis-docs
channels:
  - conda-forge
  - defaults
dependencies:
  # Base dependencies
  - python=3.11
  - pip
  - pydantic
  - jupyter

  - MDAnalysis>=2.8.0

  # Testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov

  # Documentation
  - 'mdanalysis-sphinx-theme>=1.0.1'
  - nbsphinx
  - pandoc

  # Pip-only installs
  - pip:
    - git+https://github.com/BradyAJohnston/MolecularNodes.git@v4.2.9
    - bpy
